# This contains params to be used by the stages to train or predict
base:
  random_state: 42
  test_size: 0.3

model_params:
  ElasticNet:
    # alpha: 0.5
    # l1_ratio: 0.5
    # alpha: 0.7
    # l1_ratio: 0.5
    alpha: 0.5
    l1_ratio: 0.9
